### ISSUE TITLE
Python syntax error

### ISSUE THREAD

**Issue by thh32** [Matt-Schmitz/InvestiGut#1]
The following error occured:

  File "/DATA/Hitch_analysis/InvestiGut/InvestiGut/investigut.py", line 47
    now = datetime.now().strftime(f"%y_%m_%d_%H_%M_%S")
                                                     ^
SyntaxError: invalid syntax

**Comment by Matt-Schmitz** [comment]
Did you run InvestiGut from within the conda environment? I am able to reproduce the error by running the python file with a lower python version, but not from within the investigut conda environment.
Outside of the conda environment, the missing python libraries at the top of investigut.py will not cause an error until the point in the script where they are needed.

Edit: I hadn't seen your suggested change yet when I wrote my response. Thanks for the README correction!

**Comment by thh32** [comment]
It was within the environment but it seems the environment didn't install python 3.11 for some reason. Might be the old system, checking on one of the servers

**Comment by thh32** [comment]
Resolved by recreating environment with the yaml via mamba
