### ISSUE TITLE
hard-coded paths prevent testing investigut on a different machine

### ISSUE THREAD

**Issue by cpauvert** [Matt-Schmitz/InvestiGut#5]
Hi @Matt-Schmitz,
thanks for providing the code for investigut! I tried to use it locally, but ran into an issue because of a hard-coded path that are not available on my (or anyone's) machine:

https://github.com/Matt-Schmitz/InvestiGut/blob/25b882abe1396362456728cb38e4c4c93080b381/investigut.py#L739

Incidentally, there are a couple of others you might want to fix either as relative or find a way to ship the files if that makes sense.

```
investigut.py:97:        genome_base = "//home/matt/DATA/Proteins_small4/"
investigut.py:122:        genome_base = "//home/matt/DATA/Proteins_small4/Isolate_collections/"
investigut.py:228:    #dmnd_tsv="/DATA/Matt/Diamond_databases/seaweed_50.tsv"
investigut.py:229:    #input_fasta="/DATA/Matt/Diamond_databases/seaweed.fa"
investigut.py:739:        return pd.read_excel('/DATA/Matt/mastersproject/Leviatan_species_abundance.xlsx', index_col=0) 
investigut.py:779:    lev_metadata_files = ["/home/matt/DATA/metadata/gtdbtk.bac120.summary.tsv", "/home/matt/DATA/metadata/gtdbtk.ar53.summary.tsv"]
```

Best,

**Comment by Matt-Schmitz** [comment]
Hard-coded paths have been removed now.
