### ISSUE TITLE
exposing `--threads` option from DIAMOND

### ISSUE THREAD

**Issue by cpauvert** [Matt-Schmitz/InvestiGut#6]
Hi @Matt-Schmitz,

my guess from my attempt so far is that most of the computation is done by DIAMOND, so I was surprised that you did not expose the [`--threads` option from DIAMOND,](https://github.com/bbuchfink/diamond/wiki/3.-Command-line-options#general-options) to reduce the wall-time for users. Any reason against this?

BEst,

**Comment by Matt-Schmitz** [comment]
DIAMOND sets the number of threads as the maximum number available as a default. I can still add this option, but it would only be helpful if someone wants to use fewer threads.

**Comment by cpauvert** [comment]
Alright, I was surprised when I started the program that not all threads were used, but I was not patient enough (I tried again, and correctly saw them all used).

I would argue that as a code etiquette, it's better to provide a way to use less, people might be running something else in parallel.

**Comment by Matt-Schmitz** [comment]
As different users may want to adjust different DIAMOND settings, I have changed the code to pass all arguments unknown to InvestiGut into DIAMOND. Arguments like the number of threads or DIAMOND search sensitivity will be passed on.
