### ISSUE TITLE
Fenced code blocks instead of backticks in the README

### ISSUE THREAD

**Issue by cpauvert** [Matt-Schmitz/InvestiGut#7]
HI @Matt-Schmitz;

Nothing urgent, but I think future users would like to just copy paste the instructions you provide for the set up, this is currently not possible with the backticks in markdown but if you turn them into [fenced code blocks](https://github.github.com/gfm/#fenced-code-blocks), it works

Best,

**Comment by Matt-Schmitz** [comment]
Thanks for the suggestion. I have merged the change.
